name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true            # 태그 앞에 'v' 접두사 추가 (v1.0.0)
          DEFAULT_BUMP: none     # 명시적인 커밋 메시지가 없을 경우 patch 버전 증가
          RELEASE_BRANCHES: main  # main 브랜치에서만 동작

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          VITE_KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          VITE_KAKAO_JSSDK_KEY: ${{ secrets.KAKAO_JSSDK_KEY }}
          VITE_KAKAO_RESTAPI_KEY: ${{ secrets.KAKAO_RESTAPI_KEY }}
          VITE_TMDB_KEY: ${{ secrets.TMDB_KEY }}

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist